export { default as Application } from './Application'

export { default as About } from './pages/About'
export { default as Account } from './pages/Account'
export { default as AccountHome } from './pages/AccountHome'
export { default as Forbidden } from './pages/Forbidden'
export { default as Login } from './pages/Login'
export { default as Home } from './pages/Home'
export { default as Board } from './pages/Board'
export { default as Profile } from './profile'
export { default as BoardEditor } from './profile/BoardEditor'
export { default as SuperSecretArea } from './pages/SuperSecretArea'
